### ISSUE TITLE
A模式文件匹配失败

### ISSUE THREAD

**Issue by ScottCTD** [innc11/NewUpdater#1]
我在setting.json文件编辑如下
![image](https://user-images.githubusercontent.com/35100768/100595084-6e323700-3335-11eb-9582-e5ef0894f9c8.png)
我的resource目录下有.minecraft/config/fml.toml
![image](https://user-images.githubusercontent.com/35100768/100595173-8904ab80-3335-11eb-830f-0695a420c7ab.png)
但是当客户端没有fml.toml的时候，我点更新
![image](https://user-images.githubusercontent.com/35100768/100595248-a20d5c80-3335-11eb-9f11-fc9fb7fee4e2.png)
![image](https://user-images.githubusercontent.com/35100768/100595277-a9346a80-3335-11eb-9956-3e831a65e526.png)

**Comment by innc11** [comment]
试一下添加正则表达式转义字符，因为整条路径被识别成正则表达式了，可以在所有的.前面加上反斜杠看看有没有效果

**Comment by ScottCTD** [comment]
![image](https://user-images.githubusercontent.com/35100768/100682099-4c29ca80-33b0-11eb-86f0-d9c8cfd15d6e.png)
这样也确实不行的

**Comment by innc11** [comment]
把/也加上，变成\/看看，
对了，mods文件夹可以正常更新吗
如果还是不行，请在mcbbs给我(innc)留言一下，我把qq发给你，我们在qq上细聊

**Comment by ScottCTD** [comment]
Mod文件夹正常

好的 已留言
